---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  log_level: info
  chef_license: accept-no-persist
  product_name: chef
  product_version: 14.6.47

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[ssh::default]
    attributes:
